name: bitwarden_secrets
description: Unoficial driver of the Bitwarden Secrets SDK.  Bitwarden Secrets Manager enables developers and DevOps teams to centrally store, manage, and deploy secrets at scale. 
version: 1.0.3
repository: https://github.com/PeterMcKinnis/bitwarden_secrets

platforms:
  windows: 
  linux:
  macos:
  ios:
  android:

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.0.0
